# Generated by Django 4.2.3 on 2024-01-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_ticket_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
    ]
